-- Active: 1750388007092@@127.0.0.1@3306@magicpos
USE magicpos;


DROP TABLE IF EXISTS `users`;
CREATE TABLE users (
  no BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자 고유번호(기본키)',
  id VARCHAR(50) NOT NULL COMMENT '로그인용 ID',
  username VARCHAR(100) NOT NULL COMMENT '사용자 이름',
  password VARCHAR(255) NOT NULL COMMENT '비밀번호(암호화저장)',
  birth DATE NOT NULL COMMENT '생년월일',
  gender CHAR(1) NOT NULL DEFAULT 'M' COMMENT '성별(M/F)',     -- ✅ 성별 추가
  email VARCHAR(100) NOT NULL COMMENT '이메일',
  phone VARCHAR(20) NOT NULL COMMENT '핸드폰 번호',
  memo VARCHAR(255) NULL COMMENT '사용자 메모',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '가입일자',
  `ENABLED` int NOT NULL DEFAULT 1 COMMENT '활성화 여부',
  
  PRIMARY KEY (no),
  UNIQUE KEY UK_users_id (id)
);

DROP TABLE IF EXISTS `tickets`;
CREATE TABLE tickets (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '이용권 번호',
ticket_name VARCHAR(100) NOT NULL COMMENT '이용권 이름',
time BIGINT NOT NULL COMMENT '이용권 시간',
price BIGINT NOT NULL COMMENT '이용권 가격',
PRIMARY KEY (no)
);

DROP TABLE IF EXISTS `categories`;
CREATE TABLE categories (
  no BIGINT NOT NULL AUTO_INCREMENT COMMENT '분류 번호',
  c_name VARCHAR(100) NOT NULL COMMENT '상품 분류',
  PRIMARY KEY (no)
);


DROP TABLE IF EXISTS `products`;
CREATE TABLE products (
  no BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품 번호',
  c_no BIGINT NOT NULL COMMENT '분류 번호',
  p_name VARCHAR(100) NOT NULL COMMENT '상품 이름',
  p_price BIGINT NOT NULL COMMENT '상품 가격',
  img_path VARCHAR(255) NOT NULL COMMENT '상품 이미지 경로',
  description VARCHAR(255) NOT NULL COMMENT '상품 설명',
  sell_status BOOLEAN NOT NULL COMMENT '손님 PC 노출 여부',
  stock BIGINT NOT NULL DEFAULT 0 COMMENT '상품 재고',
  PRIMARY KEY (no),
  FOREIGN KEY (c_no) REFERENCES categories(no)
    ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `seats`;
CREATE TABLE seats (
  seat_id VARCHAR(50) NOT NULL COMMENT '좌석 고유 ID (기본키)',
  seat_name VARCHAR(50) NOT NULL COMMENT '좌석 이름 또는 번호',
  seat_status BIGINT NOT NULL DEFAULT 0 COMMENT '상태(비어있음:0, 사용중:1, 고장:2, 청소중:3)',
  PRIMARY KEY (seat_id)
);


DROP TABLE IF EXISTS `orders`;
CREATE TABLE orders (
  no BIGINT NOT NULL AUTO_INCREMENT COMMENT '주문 번호',
  u_no BIGINT NOT NULL COMMENT '사용자 고유번호',
  seat_id VARCHAR(50) NOT NULL COMMENT '좌석 고유 ID',
  total_price BIGINT NOT NULL COMMENT '주문 총 금액',
  order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '주문 시간',
  payment VARCHAR(50) NOT NULL DEFAULT 'CASH' COMMENT '결제수단',
  message VARCHAR(100) NULL COMMENT '주문요청 메시지',
  order_status BIGINT NOT NULL DEFAULT 0 COMMENT '상태(주문접수:0, 준비중:1, 전달완료:2)',
  payment_status BIGINT NOT NULL DEFAULT 0 COMMENT '상태(결제전:0, 결제완료:1)',
  pay_at TIMESTAMP NULL COMMENT '결제 시각',
  cash_amount BIGINT NULL COMMENT '현금 결제 시 선택한 금액',
  PRIMARY KEY (no),
  FOREIGN KEY (u_no) REFERENCES users(no)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `carts`;
CREATE TABLE carts (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '장바구니 번호',
p_no BIGINT NOT NULL COMMENT '상품 번호',
u_no BIGINT NOT NULL COMMENT '사용자 고유번호',
quantity BIGINT NOT NULL COMMENT '상품당 장바구니 수량',
PRIMARY KEY (no),
UNIQUE KEY UK_carts_u_p (u_no, p_no),
FOREIGN KEY (p_no) REFERENCES products(no)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (u_no) REFERENCES users(no)
ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `user_tickets`;
CREATE TABLE user_tickets (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자 티켓 고유번호(기본키)',
u_no BIGINT NOT NULL COMMENT '사용자 고유번호',
t_no BIGINT NOT NULL COMMENT '이용권 번호',
remain_time BIGINT NOT NULL COMMENT '남은 이용 시간(분 단위)',
pay_at TIMESTAMP NOT NULL COMMENT '결제 시각',
payment VARCHAR(50) NOT NULL DEFAULT 'CASH' COMMENT '결제수단',
PRIMARY KEY (no),
FOREIGN KEY (u_no) REFERENCES users(no)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (t_no) REFERENCES tickets(no)
ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `auths`;
CREATE TABLE auths (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '권한 고유번호(기본키)',
u_no BIGINT NOT NULL COMMENT '사용자 고유번호',
auth VARCHAR(50) NOT NULL COMMENT '사용자권한값(예:ROLE_USER)',
PRIMARY KEY (no),
FOREIGN KEY (u_no) REFERENCES users(no)
ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `orders_details`;
CREATE TABLE orders_details (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '주문 상세 번호',
o_no BIGINT NOT NULL COMMENT '주문 번호',
p_no BIGINT NOT NULL COMMENT '상품 번호',
quantity BIGINT NOT NULL COMMENT '주문 수량',
PRIMARY KEY (no),
FOREIGN KEY (o_no) REFERENCES orders(no)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (p_no) REFERENCES products(no)
ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `seats_reservations`;
CREATE TABLE seats_reservations (
no BIGINT NOT NULL AUTO_INCREMENT COMMENT '예약 고유번호',
seat_id VARCHAR(50) NOT NULL COMMENT '좌석 고유 ID',
u_no BIGINT NOT NULL COMMENT '사용자 고유번호',
start_time TIMESTAMP NOT NULL COMMENT '예약 시작 시간',
end_time TIMESTAMP NOT NULL COMMENT '예약 종료 시간',
PRIMARY KEY (no),
FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (u_no) REFERENCES users(no)
ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `logs`;
CREATE TABLE logs (
  no BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그 번호',
  u_no BIGINT NOT NULL COMMENT '사용자 번호',
  seat_id VARCHAR(50) NULL COMMENT '좌석 번호',
  action_type VARCHAR(50) NOT NULL COMMENT '로그 종류(예: LOGIN, LOGOUT, ORDER)',
  description VARCHAR(255) NOT NULL COMMENT '로그 설명(ex. ○○○님께서 로그아웃하셨습니다.)',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '로그 기록 시간',
  PRIMARY KEY (no),
  FOREIGN KEY (u_no) REFERENCES users(no)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `chat_macros`;
CREATE TABLE chat_macros (
  no INT UNSIGNED NOT NULL AUTO_INCREMENT,
  text_message VARCHAR(255) NOT NULL,
  PRIMARY KEY (no),
  UNIQUE KEY uq_text_message (text_message) -- 같은 문구 중복 방지(옵션)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;