-- Active: 1750388007092@@127.0.0.1@3306@magicpos
DROP TABLE IF EXISTS orders_details;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS user_tickets;
DROP TABLE IF EXISTS auths;
DROP TABLE IF EXISTS seats_reservations;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS chat_macros;